spring:
  cloud:
    gateway:
      routes:
        - id: query_route
          uri: https://www.baidu.com
          predicates:
            - Query=url, baidu

        - id: query_route1
          uri: https://www.qq.com
          predicates:
            - Query=url, qq

        - id: product_route1
          uri: lb://gulimall-product
          predicates:
            - Path=/api/product/**
          filters:
            - RewritePath=/api/(?<segment>.*),//$\{segment}

        - id: admin_route
          # 负载均衡到后面的服务
          uri: lb://renren-fast
          predicates:
            - Path=/api/**
          filters:
            - RewritePath=/api/(?<segment>.*),/renren-fast/$\{segment}
          # 前端项目都带着api

