spring:
  cloud:
    gateway:
      routes:
        - id: query_route
          uri: https://www.baidu.com
          predicates:
            - Query=url, baidu
        - id: query_route1
          uri: https://www.qq.com
          predicates:
            - Query=url, qq
