spring:
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
    alicloud:
      access-key: LTAI5t8ZxBGjGzzgMjUu2C3U
      secret-key: XEe2fao6BFb6IrDzVqsPWzJWcJ9nDj
      oss:
        endpoint: oss-cn-chengdu.aliyuncs.com

  application:
    name: gulimall-third-party
server:
  port: 30000